### ISSUE TITLE
Add macOS builds

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/pcre2-feedstock#2]
Would be nice to have support for building this on macOS and release macOS builds. Not entirely sure what issues were encountered or what might need to be fixed.

**Comment by jakirkham** [comment]
Have added PRs (listed below) to each of the supported versions to build on macOS. All of them pass. Please let me know if there is anything else needed for these.

xref: https://github.com/conda-forge/pcre2-feedstock/pull/12
xref: https://github.com/conda-forge/pcre2-feedstock/pull/13
xref: https://github.com/conda-forge/pcre2-feedstock/pull/14

**Comment by dfornika** [comment]
These have all been merged, but the macOS builds aren't showing up on anaconda.org.

https://anaconda.org/conda-forge/pcre2/files

**Comment by jakirkham** [comment]
Yeah have been keeping an eye on them. Travis CI is pretty overwhelmed. They have nearly 2000 macOS builds queued ATM. Even last night (based on the western hemisphere), it still had a little over 1000 macOS jobs queued. Thinking that the issues that Travis CI had with their macOS architecture earlier this week has put them very far behind. Hopefully things will clear out and recover over the weekend.

**Comment by jakirkham** [comment]
Looks like they uploaded earlier today.
