### ISSUE TITLE
Can main branch build be restarted?

### ISSUE THREAD

**Issue by akrherz** [conda-forge/pcre2-feedstock#35]
### Comment:

Travis-CI ppc build [failed](https://github.com/conda-forge/pcre2-feedstock/runs/18163979862), can it please be restarted?

refs conda-forge/gdal-feedstock#830

**Comment by xylar** [comment]
This is causing most migration to fail:
https://conda-forge.org/status/#pcre21042

**Comment by xylar** [comment]
@xhochy, is this something you are able to do?

**Comment by xylar** [comment]
@conda-forge/pcre2, this is still giving us trouble at gdal.  Could one of you force CI to rerun so it builds the broken packages?

**Comment by jaimergp** [comment]
Should be fixed now. Please check and close if appropriate!

**Comment by akrherz** [comment]
Thank you!
