### ISSUE TITLE
Add Windows builds

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/pcre2-feedstock#8]
As PCRE2 provides CMake support, this should be relatively straightforward.

**Comment by jakirkham** [comment]
cc-ing @gillins who added Windows support to `pcre` for thoughts on this.

**Comment by jakirkham** [comment]
For reference, PR ( https://github.com/conda-forge/pcre-feedstock/pull/7 ) added Windows support to `pcre`.

**Comment by gillins** [comment]
Sorry I haven't tried to build this one yet. Let me know if you have any problems. Like you say if it already has CMake it *should* be straightforward....

**Comment by pkgw** [comment]
This got done at some point!
